name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          script: |
            if [ "$(docker ps -q -f name=aspnetapp)" ]; then
              docker stop aspnetapp
              docker rm aspnetapp
            fi

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: kuic-sena/servidor/aurelia
          tag_with_ref: true

  deploy:
    needs: [stop, publish]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          script: |
            docker login docker.pkg.github.com -u ${{ github.actor }} -p '${{ secrets.GITHUB_TOKEN }}'
            docker pull docker.pkg.github.com/kuic-sena/servidor/aurelia:latest
            docker run --name aspnetapp -p 80:80 -d --env-file /home/.env --rm docker.pkg.github.com/kuic-sena/servidor/aurelia