name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Clean instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          script: |
            bash /home/clean.sh

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: kuic-sena/servidor/aurelia
          tag_with_ref: true

  deploy:
    needs: [clean, publish]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          script: |
            docker rmi docker.pkg.github.com/kuic-sena/servidor/aurelia
            docker login docker.pkg.github.com -u ${{ github.actor }} -p '${{ secrets.GITHUB_TOKEN }}'
            docker pull docker.pkg.github.com/kuic-sena/servidor/aurelia:latest
            bash /home/run.sh